=== kevinramirez-dev/csd-430/module-9/module9/public/module9-1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT teams (team+)>
<!ELEMENT team (name, founded, stadium, players, statistics)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT founded (#PCDATA)>
<!ELEMENT stadium (#PCDATA)>
<!ELEMENT players (player+)>
<!ELEMENT player (name, position, number, nationality)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT nationality (#PCDATA)>
<!ELEMENT statistics (wins, losses, draws, points)>
<!ELEMENT wins (#PCDATA)>
<!ELEMENT losses (#PCDATA)>
<!ELEMENT draws (#PCDATA)>
<!ELEMENT points (#PCDATA)>

=== kevinramirez-dev/csd-430/module-9/module9/public/module9-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE teams SYSTEM "module9-1.dtd">
<?xml-stylesheet type="text/css" href="module9.css"?>
<teams>
  <team>
    <name>Atlanta United FC</name>
    <founded>2014</founded>
    <stadium>Mercedes-Benz Stadium</stadium>
    <players>
      <player>
        <name>Josef Martínez</name>
        <position>Forward</position>
        <number>7</number>
        <nationality>Venezuelan</nationality>
      </player>
    </players>
    <statistics>
      <wins>15</wins>
      <losses>10</losses>
      <draws>9</draws>
      <points>54</points>
    </statistics>
  </team>
  <team>
    <name>Seattle Sounders FC</name>
    <founded>2007</founded>
    <stadium>Lumen Field</stadium>
    <players>
      <player>
        <name>Raúl Ruidíaz</name>
        <position>Forward</position>
        <number>9</number>
        <nationality>Peruvian</nationality>
      </player>
    </players>
    <statistics>
      <wins>17</wins>
      <losses>8</losses>
      <draws>9</draws>
      <points>60</points>
    </statistics>
  </team>
</teams>
